// AUTO-GENERATED by scripts/fetch-images.mjs — do not edit by hand.
// Run `npm run images` to refresh. Photos come from Wikimedia Commons;
// author and licence are recorded verbatim from the file's Commons page.

import type { Photo } from "./types";

export const generatedPhotos: Photo[] = [
  {
    "id": "neuschwanstein-hero",
    "src": "/images/destinations/neuschwanstein-hero.jpg",
    "width": 2400,
    "height": 1793,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJZgCdAYuvkk573xp4AD+kasKbeEa+GQgnQiSY8hb+f1uiif/h5f1Pp46r49thnPhybrS1lOgvn9SFypGrZbe7RThrrDdsC7l/vBSAAA=",
    "credit": {
      "author": "Thomas Wolf , www.foto-tw.de",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schloss_Neuschwanstein_2013.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "neuschwanstein-2",
    "src": "/images/destinations/neuschwanstein-2.jpg",
    "width": 2400,
    "height": 1593,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAQCdASoQAAsAA4BaJbACdADaDpCYAAD+JpMKBq1ME8jBVA/wjCtDa87eHCYmtm/qhPhEN8r9RlOAcMaL/54SFACTqI65QXPvPo7dJvOm18ixVzZ1zfSeW5rs/JIAAAA=",
    "credit": {
      "author": "Thomas Wolf , www.foto-tw.de",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schloss_Hohenschwangau_2021.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "neuschwanstein-3",
    "src": "/images/destinations/neuschwanstein-3.jpg",
    "width": 2400,
    "height": 1477,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoQAAoAA4BaJYgCdAEPScBcqS4AAP4nnN+8qGeVfNqP+U6hW4pdXyYzYjFH6gC0w6uKUAAA",
    "credit": {
      "author": "Carsten Steger",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_image_of_the_Alpsee_(view_from_the_southwest).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "koenigssee-hero",
    "src": "/images/destinations/koenigssee-hero.jpg",
    "width": 2400,
    "height": 3200,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoBnABt2Qgt+uUq5M80A2cAA/pGV5N/T+7/Cm+xG/JCsba9xpcSmcxgBNLruT2Ak0PvgCmzfS0HwWXyvbmgxU8LJLnGFJ0NwSR7LPw5GbCGrZ9TEjbQ1Sib/xDzaeWaaQYe250I/ntAAAA==",
    "credit": {
      "author": "Mtt1734",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:K%C3%B6nigsee_in_Bayern.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "koenigssee-2",
    "src": "/images/destinations/koenigssee-2.jpg",
    "width": 2400,
    "height": 1796,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJZQCw7ELM8sWrlAAAP7F/STGfZGckK3Kp0fQUO88UtoObg9Huhapru3UBUHJeMljzDGYRirUN/7vqLND4MoqtW4xY+yUFwAAAA==",
    "credit": {
      "author": "Waldemar L",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Die_Kirche_von_St._Bartholom%C3%A4_am_K%C3%B6nigssee..jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "koenigssee-3",
    "src": "/images/destinations/koenigssee-3.jpg",
    "width": 2400,
    "height": 1351,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJYgCdADvZ8M2AAD+xeXEK81x4UEm8XL/kI3xtZ59k2zR1lrFAUHNz5lP6KP6+Oopwsb1u0otRykYZbwAAA==",
    "credit": {
      "author": "Jörg Braukmann",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Watzmann_von_Norden.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rothenburg-hero",
    "src": "/images/destinations/rothenburg-hero.jpg",
    "width": 2400,
    "height": 1607,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAQCdASoQAAsAA4BaJQBOgBKSgADgBpkpp+Rg8fCi8zqFBy/ZaqziYsd8+iUc8nhjaUWyqbYkUBA3wmYNueaG1QkCMwQMzVfGrNy/DcTW4ExkAAA=",
    "credit": {
      "author": "Berthold Werner",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Rothenburg_BW_4.JPG",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rothenburg_BW_4.JPG",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rothenburg-2",
    "src": "/images/destinations/rothenburg-2.jpg",
    "width": 979,
    "height": 1342,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoQABYAPu1iqU2ppaQiMAgBMB2JQBYdhDwJvOw2giCyJCsOOIAA/lHlIjuboTXVu0X2GEwSLxzCoIrfRSzpjhRkRf3Jx0P83sMW6TQ4TYiQgfC6AVOAAA==",
    "credit": {
      "author": "NordNordWest",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Karte_Romantische_Stra%C3%9Fe_2016.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rothenburg-3",
    "src": "/images/destinations/rothenburg-3.jpg",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAsAA4BaJbACdAEOPDZQ3YAA+OX1hkTsl1a01/+AG9Q+9auiclx5FqCfLunjhKf5UwdB4OSf7cLbybyAxObC05qHg5hSjLIaoT0yL1H+2vZkAAA=",
    "credit": {
      "author": "Mylius",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dinkelsbuehl_Kirchturm_West.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "bamberg-hero",
    "src": "/images/destinations/bamberg-hero.jpg",
    "width": 1791,
    "height": 1029,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJbACdAEK/UIBWAAA/lv4FvLAoSmI3AgjTRZvrFAD7clegpi6mF8lFoJQ+UMdaSkY01O4JnW+66CzoU5db0rBrPGmazcbnNpAq6AA",
    "credit": {
      "author": "Reinhard Kirchner",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kloster_Michaelsberg_Parkseite.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "bamberg-2",
    "src": "/images/destinations/bamberg-2.jpg",
    "width": 2400,
    "height": 1766,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJZgCdAED+gOFdB8AAPHTWh2kjLyF9xAUetCZ6UGoU/UFHgd3N3DBqxJNvArSpBdwGrT8xHftulEqyUdn8h30Lc8e+FMmYAAAAA==",
    "credit": {
      "author": "Berthold Werner",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Bamberger_Dom_BW_6.JPG",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bamberger_Dom_BW_6.JPG",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "bamberg-3",
    "src": "/images/destinations/bamberg-3.jpg",
    "width": 2048,
    "height": 1536,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAwAA4BaJaACdAEPD2SAN5agAP4HtHN87eqGCCG/PDBdrQYnuMOCssO3zHj0ZTJZ1lLiGlPIJTYrWKZLqS6DdvnirYRi4M0MPPo07qroESUXFbzUZ404AAA=",
    "credit": {
      "author": "Moehri",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:M%C3%B6hrendorf_Wasserr%C3%A4der_Schmiedsrad.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "black-forest-2",
    "src": "/images/destinations/black-forest-2.jpg",
    "width": 800,
    "height": 531,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAsAA4BaJZwAAubQobOR2AD+7ip6swUuQfH53zsqLfUAIhFFpS0d4HWoFzD2QAA=",
    "credit": {
      "author": "User Christian.maier on de.wikipedia",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Titisee-blick_von_hochfirst.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "lake-constance-3",
    "src": "/images/destinations/lake-constance-3.jpg",
    "width": 1986,
    "height": 1343,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAsAA4BaJbACdAEO9EZLmAAA/urzRwipSpBjHf3gcHz9F/SqK/BimWTBLZeLrX8a6G1w9kQMAAAA",
    "credit": {
      "author": "Edda Praefcke",
      "license": "CC BY 2.5",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lindau_Insel_Luftbild3.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "moselle-hero",
    "src": "/images/destinations/moselle-hero.jpg",
    "width": 2263,
    "height": 2242,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQABAAA4BaJaACdAD0nTnTpwAA/vU2ZqTuG7z/cpBpLpgfaNF/yC8iv8vjQmwVH2kx93YUDy/7zNnQvNjgJgAL54ZYwJ2L6AijyuzLsopV/tAA",
    "credit": {
      "author": "Areks",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schweicher_Annaberg.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "berlin-hero",
    "src": "/images/destinations/berlin-hero.jpg",
    "width": 1920,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAsAA4BaJbACdDiAN4bBH8W5W9s4AP6DaNxwinpxGrPxsHEFxgonS3It0eSP7I76LEIh2UKEHf7tUZSfUoFyqa17/nYB5V8qxOVH5vPQn6X+rvJxKr0OwH6iSd7JoAA=",
    "credit": {
      "author": "Thomas Wolf , www.foto-tw.de",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brandenburger_Tor_abends.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "saxon-switzerland-3",
    "src": "/images/destinations/saxon-switzerland-3.jpg",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAsAA4BaJQBdgCP85emZ0d8gAAD+7BJyEzb728mfXNQoR6HNO0/7G+PeEgWf1QzpUAFsz/aRLypI6DLWZYvMImv0gAAA",
    "credit": {
      "author": "Fritz-Gerald Schröder",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_photo_of_Festung_K%C3%B6nigstein,_October_2008.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "harz-hero",
    "src": "/images/destinations/harz-hero.jpg",
    "width": 786,
    "height": 544,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAwAgCdASoQAAsAA4BaJZgCdGuAAs28Qthl8AD93itJImZ+jMmgFZ/DQrxU/qgOgfRJFO95j/dFZ9dcThTethbHIOAAAA==",
    "credit": {
      "author": "Axel Hindemith",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Brocken_vom_Torfhaus.jpg",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brocken_vom_Torfhaus.jpg",
      "source": "Wikimedia Commons"
    }
  }
];
