// AUTO-GENERATED by scripts/fetch-images.mjs — do not edit by hand.
// Run `npm run images` to refresh. Photos come from Wikimedia Commons;
// author and licence are recorded verbatim from the file's Commons page.

import type { Photo } from "./types";

export const generatedPhotos: Photo[] = [
  {
    "id": "neuschwanstein-hero",
    "src": "/images/destinations/neuschwanstein-hero.jpg",
    "width": 2400,
    "height": 1793,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJZgCdAYuvkk573xp4AD+kasKbeEa+GQgnQiSY8hb+f1uiif/h5f1Pp46r49thnPhybrS1lOgvn9SFypGrZbe7RThrrDdsC7l/vBSAAA=",
    "credit": {
      "author": "Thomas Wolf , www.foto-tw.de",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schloss_Neuschwanstein_2013.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "neuschwanstein-2",
    "src": "/images/destinations/neuschwanstein-2.jpg",
    "width": 2400,
    "height": 1593,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAQCdASoQAAsAA4BaJbACdADaDpCYAAD+JpMKBq1ME8jBVA/wjCtDa87eHCYmtm/qhPhEN8r9RlOAcMaL/54SFACTqI65QXPvPo7dJvOm18ixVzZ1zfSeW5rs/JIAAAA=",
    "credit": {
      "author": "Thomas Wolf , www.foto-tw.de",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schloss_Hohenschwangau_2021.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "neuschwanstein-3",
    "src": "/images/destinations/neuschwanstein-3.jpg",
    "width": 2400,
    "height": 1477,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoQAAoAA4BaJYgCdAEPScBcqS4AAP4nnN+8qGeVfNqP+U6hW4pdXyYzYjFH6gC0w6uKUAAA",
    "credit": {
      "author": "Carsten Steger",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_image_of_the_Alpsee_(view_from_the_southwest).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "koenigssee-hero",
    "src": "/images/destinations/koenigssee-hero.jpg",
    "width": 2400,
    "height": 1568,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAoAA4BaJbACdAEOglLEbsAAAPjIOm7TstwBAESy84KdCp/YnV/URHl+T8gXlE41TfFXoaSZ+1FV2bkrMxaxCQsnsMGoPzgAAA==",
    "credit": {
      "author": "Jörg Braukmann",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Herbst_in_den_Berchtesgadener_Alpen.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "koenigssee-2",
    "src": "/images/destinations/koenigssee-2.jpg",
    "width": 2400,
    "height": 1796,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJZQCw7ELM8sWrlAAAP7F/STGfZGckK3Kp0fQUO88UtoObg9Huhapru3UBUHJeMljzDGYRirUN/7vqLND4MoqtW4xY+yUFwAAAA==",
    "credit": {
      "author": "Waldemar L",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Die_Kirche_von_St._Bartholom%C3%A4_am_K%C3%B6nigssee..jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "koenigssee-3",
    "src": "/images/destinations/koenigssee-3.jpg",
    "width": 2400,
    "height": 3200,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCdMoBnABt2Qgt+uUq5M80A2cAA/pGV5N/T+7/Cm+xG/JCsba9xpcSmcxgBNLruT2Ak0PvgCmzfS0HwWXyvbmgxU8LJLnGFJ0NwSR7LPw5GbCGrZ9TEjbQ1Sib/xDzaeWaaQYe250I/ntAAAA==",
    "credit": {
      "author": "Mtt1734",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:K%C3%B6nigsee_in_Bayern.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rothenburg-hero",
    "src": "/images/destinations/rothenburg-hero.jpg",
    "width": 2400,
    "height": 1607,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAQCdASoQAAsAA4BaJQBOgBKSgADgBpkpp+Rg8fCi8zqFBy/ZaqziYsd8+iUc8nhjaUWyqbYkUBA3wmYNueaG1QkCMwQMzVfGrNy/DcTW4ExkAAA=",
    "credit": {
      "author": "Berthold Werner",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Rothenburg_BW_4.JPG",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rothenburg_BW_4.JPG",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rothenburg-2",
    "src": "/images/destinations/rothenburg-2.jpg",
    "width": 1728,
    "height": 2286,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JYwBV0AebiQ763Agc5wVgAP7VFpEgAiLM7AooGOu8UxzBAx9WD6sfpUjER/fnoMRm2+s3SMxmPBgz4/NLNmI+95WDMMtPaIsoHu2HoWAjBrGsKX33udEg4DyWO6g/nXwySN3X/ZmH2DG2rsJqTpsAAAA=",
    "credit": {
      "author": "Mussklprozz",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:N%C3%B6rdlingenDanielBlickS%C3%BCden.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rothenburg-3",
    "src": "/images/destinations/rothenburg-3.jpg",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAsAA4BaJbACdAEOPDZQ3YAA+OX1hkTsl1a01/+AG9Q+9auiclx5FqCfLunjhKf5UwdB4OSf7cLbybyAxObC05qHg5hSjLIaoT0yL1H+2vZkAAA=",
    "credit": {
      "author": "Mylius",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dinkelsbuehl_Kirchturm_West.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "bamberg-hero",
    "src": "/images/destinations/bamberg-hero.jpg",
    "width": 1791,
    "height": 1029,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJbACdAEK/UIBWAAA/lv4FvLAoSmI3AgjTRZvrFAD7clegpi6mF8lFoJQ+UMdaSkY01O4JnW+66CzoU5db0rBrPGmazcbnNpAq6AA",
    "credit": {
      "author": "Reinhard Kirchner",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kloster_Michaelsberg_Parkseite.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "bamberg-2",
    "src": "/images/destinations/bamberg-2.jpg",
    "width": 2400,
    "height": 1766,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJZgCdAED+gOFdB8AAPHTWh2kjLyF9xAUetCZ6UGoU/UFHgd3N3DBqxJNvArSpBdwGrT8xHftulEqyUdn8h30Lc8e+FMmYAAAAA==",
    "credit": {
      "author": "Berthold Werner",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Bamberger_Dom_BW_6.JPG",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bamberger_Dom_BW_6.JPG",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "bamberg-3",
    "src": "/images/destinations/bamberg-3.jpg",
    "width": 2161,
    "height": 3525,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwAwCdASoQABoAPu1mq04ppaQiMAgBMB2JbACdMoAJ9CENWPOTUYsAAP7adsoqUh1kKMty6CYCjfLHZSJyvVEWWOORPSFCBww+PPQWw994BF3P/wQYfq+1IKOqIm7+2UJ1flBRxJ+6GnlkKvkChyfzmWBkWQs0DMhuugUnbLx1MKXwm2mhgSMUVFfNhiaWRl0dW/Nc4AA=",
    "credit": {
      "author": "Berthold Werner",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Bamberg_Sankt_Michael_BW_12.JPG",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bamberg_Sankt_Michael_BW_12.JPG",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "black-forest-hero",
    "src": "/images/destinations/black-forest-hero.jpg",
    "width": 2400,
    "height": 1428,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkAA4BaJQBOj+ADA0jXjMAA/I/QR8OW39762j1pXZgWkMWOj0hltb42VWisuNwOQFDpcrBfAAAA",
    "credit": {
      "author": "MWolf89",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blick_vom_Hohfelsen.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "black-forest-2",
    "src": "/images/destinations/black-forest-2.jpg",
    "width": 800,
    "height": 531,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAsAA4BaJZwAAubQobOR2AD+7ip6swUuQfH53zsqLfUAIhFFpS0d4HWoFzD2QAA=",
    "credit": {
      "author": "User Christian.maier on de.wikipedia",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Titisee-blick_von_hochfirst.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "black-forest-3",
    "src": "/images/destinations/black-forest-3.jpg",
    "width": 2400,
    "height": 3200,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwAAUqUKK7Rx3e4LkW4AAP7pHKOKCT1qy/vIR7rcqTV7K4hx8T/g5wU6TMu8MbORGWux/JoEcUOvV5JIixspTa6O1UBFvvrBcHm68XVkZ7pOwFSUZb5lhIEthLFYAi7XZLIAAAA=",
    "credit": {
      "author": "MargaritaGagina",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Triberg_waterfall.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "heidelberg-hero",
    "src": "/images/destinations/heidelberg-hero.jpg",
    "width": 2400,
    "height": 1364,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJQBOgCHczeb5gAD+75EIQ7RKwrNfDtcJcrkmTE9u3ZUOwrqBTxIT/HDGXLQjtV0zAxLIjfzcEYGAAAA=",
    "credit": {
      "author": "Motatcho",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Heidelberg-2726936.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "heidelberg-2",
    "src": "/images/destinations/heidelberg-2.jpg",
    "width": 2400,
    "height": 1266,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAgAA4BaJYgAAudvNOOQp4AAzKNvtgQ6Xnj+CJjTu7vDnp46N8cE5tXwtdgA1CTLS29iMWfpiNzVAAA=",
    "credit": {
      "author": "Jörg Braukmann",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:K%C3%B6nigstuhl,_Heidelberg,_U-17.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "heidelberg-3",
    "src": "/images/destinations/heidelberg-3.jpg",
    "width": 2304,
    "height": 1130,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAgAA4BaJYwCdADhApeYAAD9mF6Lf8/vwbHHmI9LjaYWsNau1AR0Tz+tVjwcD1AaQO1O6HYICBIjQuhCBr2AAAA=",
    "credit": {
      "author": "BishkekRocks",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alte_Br%C3%BCcke_Heidelberg.JPG",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "lake-constance-hero",
    "src": "/images/destinations/lake-constance-hero.jpg",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJYwCdAEPCRwX7H0nYADOOYJ3t976WiBYDpd9yLUApCjPCZYb1NvSLPiuhapnVf7J+Mse3eGMrmGjhmqNF5cUgOl5lM31cT2pYssAAAA=",
    "credit": {
      "author": "Win7sony",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ueberlingen_promenade_viewed_from_a_departing_ship.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "lake-constance-2",
    "src": "/images/destinations/lake-constance-2.jpg",
    "width": 2400,
    "height": 1233,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAgAA4BaJagCdAEQ78k/FgD+oNZxxlxmL0m5hzzx6U2N6zRNDQ4Gg4t3tQ8WZEFe7dFwuHNd/AAA",
    "credit": {
      "author": "Holger Uwe Schmitt",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aus_dem_Zeppelin_fotografiert,_Insel_Mainau,_Bodensee._10.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "lake-constance-3",
    "src": "/images/destinations/lake-constance-3.jpg",
    "width": 1986,
    "height": 1343,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAsAA4BaJbACdAEO9EZLmAAA/urzRwipSpBjHf3gcHz9F/SqK/BimWTBLZeLrX8a6G1w9kQMAAAA",
    "credit": {
      "author": "Edda Praefcke",
      "license": "CC BY 2.5",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lindau_Insel_Luftbild3.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rhine-valley-hero",
    "src": "/images/destinations/rhine-valley-hero.jpg",
    "width": 2400,
    "height": 1550,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAoAA4BaJagCdH8AGA7nmSgAAM3zw+m3umpT9QHiUIjKC0YRgHovPdjlqrruWY8vhfbBCCJ7c9cDC5egvwFFJzak6ZWjgAA=",
    "credit": {
      "author": "Alexander Hoernigk",
      "license": "CC BY 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:St.Goarshausen_Loreley_Burg_Katz_2016-03-27-17-13-57.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rhine-valley-2",
    "src": "/images/destinations/rhine-valley-2.jpg",
    "width": 2400,
    "height": 1136,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAgAA4BaJQBOgB0jup5y9AAA/uem7W+JODAWeFxxTN81Tx/lKgTddPxU8bodbyBtQuqfwyHkYmN2g+ZgAA==",
    "credit": {
      "author": "imehling",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Loreley,_Rhine,_Castle_Katz.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "rhine-valley-3",
    "src": "/images/destinations/rhine-valley-3.jpg",
    "width": 2400,
    "height": 1727,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAA4BaJZACdAYv1aCGAzIaAP62F1YbK6VcGaCzAtfno96x6+z3+Mr/kHPOdBHvy3VhRrbbcnHbs3g/kR8DSRwl6H+j27bmZU/OSVe5HOo/71/+VCoXCOBP64AA",
    "credit": {
      "author": "Jörg Braukmann",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Burg_Pfalzgrafenstein_2017.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "moselle-hero",
    "src": "/images/destinations/moselle-hero.jpg",
    "width": 2263,
    "height": 2242,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQABAAA4BaJaACdAD0nTnTpwAA/vU2ZqTuG7z/cpBpLpgfaNF/yC8iv8vjQmwVH2kx93YUDy/7zNnQvNjgJgAL54ZYwJ2L6AijyuzLsopV/tAA",
    "credit": {
      "author": "Areks",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schweicher_Annaberg.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "moselle-2",
    "src": "/images/destinations/moselle-2.jpg",
    "width": 2400,
    "height": 1613,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAsAA4BaJQBOgB58Q1nkwgAA+OTPK5Yx3l2HUIRGMVWiCMOowRQ6sG8mCbPrwOv0CGgXEgSxqNG6NzEI+AAA",
    "credit": {
      "author": "Carsten Steger",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_image_of_the_Moselle_in_Bernkastel-Kues_(view_from_the_southeast).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "moselle-3",
    "src": "/images/destinations/moselle-3.jpg",
    "width": 2400,
    "height": 3373,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBACdASoQABYAPu1iqU2ppaOiMAgBMB2JYwAAW+zoaWDXyqn41x+nQAD+6OKSsvPfRdCl3fALSOGq6FvWNcojX4qdTQiNO13q+qCb8yrxYWADHB4Ud9ytmRiH0oyoLNT8fv2HWd6JqOSYW0AAAA==",
    "credit": {
      "author": "Clementp.fr",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Le_ch%C3%A2teau_d%27Eltz_(Burg_Eltz)_en_allemagne_(cropped).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "cologne-hero",
    "src": "/images/destinations/cologne-hero.jpg",
    "width": 2400,
    "height": 1325,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAkAA4BaJZQCdAELRogokAD7IuSjYAv2r93wPm5B6ABJVhxCSB4i6KuNAAAA",
    "credit": {
      "author": "Martin Falbisoner",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kranh%C3%A4user_Cologne,_April_2018_-01.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "cologne-2",
    "src": "/images/destinations/cologne-2.jpg",
    "width": 2000,
    "height": 1452,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwAA4BaJYgCdAC3svMlPoAA/eOVe+6O0fApIWjcwolO8D0uXJg/+GeRB4Vu4ybQKKDarPaw/CZ5gFPQin2RZ2Ri/Ow1AAPBbz7/AAA=",
    "credit": {
      "author": "Raimond Spekking",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hohenzollernbr%C3%BCcke_K%C3%B6ln_von_oben.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "cologne-3",
    "src": "/images/destinations/cologne-3.jpg",
    "width": 2400,
    "height": 3895,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoQABoALrV2u12jqampiYC0S2AE6ZQjADjAAqfqdaoIb6ggAP7nFUoLgqzxsZ6F0C33AIkrt4dJxZuPFfD/1RNR/PqCaMabNduQ1/uxvDHS6on9hkTFBVGOetCTJBeH2zr1R0vA1cSAhl/7Z4Cj78Txrml4jUzFvDh39zzfpzNvCpbb1imuDjNDKjmX6na38mecAA==",
    "credit": {
      "author": "Raimond Spekking",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:K%C3%B6lner_Dom_-_Westfassade_2022_ohne_Ger%C3%BCst-0968_b.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "berlin-hero",
    "src": "/images/destinations/berlin-hero.jpg",
    "width": 1920,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAsAA4BaJbACdDiAN4bBH8W5W9s4AP6DaNxwinpxGrPxsHEFxgonS3It0eSP7I76LEIh2UKEHf7tUZSfUoFyqa17/nYB5V8qxOVH5vPQn6X+rvJxKr0OwH6iSd7JoAA=",
    "credit": {
      "author": "Thomas Wolf , www.foto-tw.de",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brandenburger_Tor_abends.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "berlin-2",
    "src": "/images/destinations/berlin-2.jpg",
    "width": 2400,
    "height": 1621,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAsAA4BaJaACdGuAAqyxUyhMAAD93lPUOBAa5UqIipAddqb7tlfKQO/9CL50l7/9mCqiM0/E70PF+JghIfYQcioeYTP5AAA=",
    "credit": {
      "author": "Thomas Wolf , www.foto-tw.de",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Berlin_Museumsinsel_Fernsehturm.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "berlin-3",
    "src": "/images/destinations/berlin-3.jpg",
    "width": 2400,
    "height": 1399,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCHQXdH+AAD8j+onGQHaT75ZLwj9ntRZcSmTYIJM9Oa2HeQppa46fzW3CD9uDXS4dVyKKDJsATry5VUmCgAAAA==",
    "credit": {
      "author": "File:Museumsinsel Berlin Juli 2021 1 (cropped).jpg : Kasa Fue derivative work: Georgfotoart",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Museumsinsel_Berlin_Juli_2021_1_(cropped)_b.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "dresden-hero",
    "src": "/images/destinations/dresden-hero.jpg",
    "width": 2400,
    "height": 1425,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJaACdADhIHHWgADxxvpUFVQ/WjfGZ/lx8YXMDu6v2L9FyDaaR2nBXRlnY4n1i3MU5KZDQShTOF5dTvj5EpKgAAA=",
    "credit": {
      "author": "User:Kolossos",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:DD-Schloss-gp.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "dresden-2",
    "src": "/images/destinations/dresden-2.jpg",
    "width": 2048,
    "height": 1366,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAsAA4BaJZgCdEf/gZhLOyKoAN2WRAUdIrbtWy1pB6N4sZD5VteVX1+7xhj2XEsihnCRBkIhPveCh+Z9ZC1xTg4v4AAA",
    "credit": {
      "author": "Avda",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dresden_-_Semperoper_-_2013.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "dresden-3",
    "src": "/images/destinations/dresden-3.jpg",
    "width": 2400,
    "height": 3558,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQAwCdASoQABgAPu1iqk2ppaQiMAgBMB2JagCdAB4/4lVzBrvIKpoA/oFGB0dvtVnMCvshWUKFJhJmXSgpnaojmMDKCK4jCWctz4YQybbFrx/LHSCyz/Wslo32trhAnmcvXbSqWLUdtj3otKt9ej4YsViI3h8n1eJpYhSSlo4AAA==",
    "credit": {
      "author": "Netopyr",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:100130_150006_Dresden_Frauenkirche_winter_blue_sky-2.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "saxon-switzerland-hero",
    "src": "/images/destinations/saxon-switzerland-hero.jpg",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAsAA4BaJQBOgA7y6luQAP4FoAtl6l5s4y6wHMx7neDGX+tTIa00CgpnjnSHHeTXvLtH0X6vRTogNbcnox85LH1adzLIh44kvQAA",
    "credit": {
      "author": "A.Savin",
      "license": "FAL",
      "licenseUrl": "http://artlibre.org/licence/lal/en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rathen_und_Elbsandsteingebirge_asv2022-08_img04.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "saxon-switzerland-2",
    "src": "/images/destinations/saxon-switzerland-2.jpg",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoQAAsAA4BaJbACdGuAAt2+PbupTAD+BVtOHHFr46qsk2Rn+0ST0/MdnScUPjyiMxFYwlHn8Tc3jzyTJ1zvzutuwAA=",
    "credit": {
      "author": "Merops",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lilienstein_Saxon_Switzerland.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "saxon-switzerland-3",
    "src": "/images/destinations/saxon-switzerland-3.jpg",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAsAA4BaJQBdgCP85emZ0d8gAAD+7BJyEzb728mfXNQoR6HNO0/7G+PeEgWf1QzpUAFsz/aRLypI6DLWZYvMImv0gAAA",
    "credit": {
      "author": "Fritz-Gerald Schröder",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_photo_of_Festung_K%C3%B6nigstein,_October_2008.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "hamburg-hero",
    "src": "/images/destinations/hamburg-hero.jpg",
    "width": 2400,
    "height": 1434,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAQCdASoQAAoAA4BaJbACdH8AB2ZsAAD+3X6mINa//1xbrdS5z7VkaRoG6gKdBNLBzVml+SNoQRw+EZS/O8mKSec11gfVr3+T6j6yEv1Y4/6jMM/gfM0wOz++mUJB5/4bZQAA",
    "credit": {
      "author": "Thomas Wolf , www.foto-tw.de",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Speicherstadt_abends.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "hamburg-2",
    "src": "/images/destinations/hamburg-2.jpg",
    "width": 1920,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAsAA4BaJQBOgBZrFhCIceAA/UbVrZwhHJmjDGv+VGZGdXD2lZNapqlwrS25qVvEnY9GcdDms70dcE/1sbZqgAA=",
    "credit": {
      "author": "Evgenii Salganik",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elbphilharmonie_2025.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "hamburg-3",
    "src": "/images/destinations/hamburg-3.jpg",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAsAA4BaJZwAAlmFDhWAAP6QnmIzhoiS42h7Lvr3bUGtqsH4abKM7O7BvXxaN+ALxm5C2C4wlFwN9VT9TFbUWWELAIAA",
    "credit": {
      "author": "Dietmar Rabich",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hamburg,_Landungsbr%C3%BCcken_--_2016_--_3131-7.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ruegen-hero",
    "src": "/images/destinations/ruegen-hero.jpg",
    "width": 2400,
    "height": 1656,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAsAA4BaJZQCsADp5colLIAA/t9+cGBexBBT9kX1pC4D6jANualqe7L2NhLpTYr1rmv2bSWwPhFmu7I4gI2jlfv+oAAA",
    "credit": {
      "author": "Moahim",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2019_-_Nationalpark_Jasmund_-_03.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ruegen-2",
    "src": "/images/destinations/ruegen-2.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAwAA4BaJbACdAD0L9ZeaQAA/o04AGHbobF3hrRCutRZAOPVFa/QiEUNkyzsQPwP9y/+Q84Hsi6peir3lMjcGsR2UZHKy2AAAA==",
    "credit": {
      "author": "Haloorange",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Insel_R%C3%BCgen-Strand_von_Sellin.jpg",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Insel_R%C3%BCgen-Strand_von_Sellin.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ruegen-3",
    "src": "/images/destinations/ruegen-3.jpg",
    "width": 2400,
    "height": 1354,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAkAA4BaJQBOgCKUJrKYAAD+4+mUNFuQHqgwTwvnvea4VrKjxkurCEZwxvPC0s97LwAA",
    "credit": {
      "author": "Klugschnacker",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Binz_(2011-05-21)_05.JPG",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "harz-hero",
    "src": "/images/destinations/harz-hero.jpg",
    "width": 1500,
    "height": 1000,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAsAA4BaJQBOgCHcSZ+aMwAA/lIYnS3ta9ytRGPpePQXAN0j+5BRSdblGVlVGsQhUnrkPFZSiPYTOwAAAA==",
    "credit": {
      "author": "Andreas Tille",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:WernigerodeCastleWinter.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "harz-2",
    "src": "/images/destinations/harz-2.jpg",
    "width": 2400,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAgAA4BaJQBOgCIKAB3vgAD8jC6Fc1EE6NTIg948A1DU80LOmlRKmiAonYP+66jpGyzFfXWPwwAA",
    "credit": {
      "author": "A.Savin",
      "license": "FAL",
      "licenseUrl": "http://artlibre.org/licence/lal/en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quedlinburg_asv2018-10_img11_Markt.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "harz-3",
    "src": "/images/destinations/harz-3.jpg",
    "width": 786,
    "height": 544,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAwAgCdASoQAAsAA4BaJZgCdGuAAs28Qthl8AD93itJImZ+jMmgFZ/DQrxU/qgOgfRJFO95j/dFZ9dcThTethbHIOAAAA==",
    "credit": {
      "author": "Axel Hindemith",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Brocken_vom_Torfhaus.jpg",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brocken_vom_Torfhaus.jpg",
      "source": "Wikimedia Commons"
    }
  }
];
